import { getDefaultHealthForDomain } from './domain-health-helpers'

export function getSeedRecords() {
  const serverMainVps = {
    id: 'server_main_vps',
    name: 'Main VPS Ryzen Luxvps',
    provider: 'LUX VPS',
    packageName: 'Ryzen Starter',
    ipAddress: '45.86.155.120',
    cpu: 3,
    ramGb: 10,
    storage: '75 GB NVMe',
    bandwidth: 'Unlimited',
    os: 'Ubuntu 24.04',
    location: 'Germany',
    hostedServices: ['Founder OS', 'PakTrendz', 'n8n', 'OpenHands'],
    connectedProjectIds: ['project_paktrendz', 'project_founder_os'],
    cost: 1870,
    currency: 'PKR',
    renewalDate: '2027-10-16',
    expiryDate: '2027-10-16',
    status: 'Active',
    notes: 'Primary production VPS for founder projects.',
  }

  const domains = [
    {
      id: 'domain_viralpk',
      name: 'viralpk.com',
      provider: 'SpaceShip',
      cost: 2830,
      currency: 'PKR',
      renewalDate: '2027-05-10',
      expiryDate: '2027-05-10',
      status: 'Active',
      notes: 'PakTrendz production domain.',
      connectedProjectIds: ['project_paktrendz'],
      connectedServerIds: ['server_main_vps'],
      connectedRepoIds: ['repo_paktrendz'],
      health: getDefaultHealthForDomain('viralpk.com'),
      subdomains: [],
    },
    {
      id: 'domain_founder_os',
      name: 'founder-os.chaudhery.com',
      provider: 'Cloudflare',
      cost: 0,
      currency: 'PKR',
      renewalDate: '',
      expiryDate: '',
      status: 'Active',
      notes: 'Founder OS live subdomain.',
      connectedProjectIds: ['project_founder_os'],
      connectedServerIds: ['server_main_vps'],
      connectedRepoIds: ['repo_founder_os'],
      health: getDefaultHealthForDomain('founder-os.chaudhery.com'),
      subdomains: [],
    },
    {
      id: 'domain_chaudhery',
      name: 'chaudhery.com',
      provider: 'Namecheap',
      cost: 3600,
      currency: 'PKR',
      renewalDate: '2026-11-20',
      expiryDate: '2026-11-20',
      status: 'Active',
      notes: 'Personal domain.',
      connectedProjectIds: [],
      connectedServerIds: [],
      connectedRepoIds: [],
      health: getDefaultHealthForDomain('chaudhery.com'),
      subdomains: [],
    },
    {
      id: 'domain_backupproof',
      name: 'backupproof.dev',
      provider: 'Porkbun',
      cost: 1200,
      currency: 'PKR',
      renewalDate: '2027-02-14',
      expiryDate: '2027-02-14',
      status: 'Active',
      notes: 'BackupProof planning domain.',
      connectedProjectIds: ['project_backupproof'],
      connectedServerIds: [],
      connectedRepoIds: ['repo_backupproof'],
      health: getDefaultHealthForDomain('backupproof.dev'),
      subdomains: [],
    },
    {
      id: 'domain_unitystore',
      name: 'unitystore.com.pk',
      provider: 'PKNIC',
      cost: 2400,
      currency: 'PKR',
      renewalDate: '2026-09-01',
      expiryDate: '2026-09-01',
      status: 'Expiring Soon',
      notes: '',
      connectedProjectIds: [],
      connectedServerIds: [],
      connectedRepoIds: [],
      health: getDefaultHealthForDomain('unitystore.com.pk'),
      subdomains: [],
    },
    {
      id: 'domain_kotaddu',
      name: 'kotaddu.pk',
      provider: 'PKNIC',
      cost: 1800,
      currency: 'PKR',
      renewalDate: '2027-01-15',
      expiryDate: '2027-01-15',
      status: 'Active',
      notes: '',
      connectedProjectIds: [],
      connectedServerIds: [],
      connectedRepoIds: [],
      health: getDefaultHealthForDomain('kotaddu.pk'),
      subdomains: [],
    },
  ]

  const repos = [
    {
      id: 'repo_paktrendz',
      name: 'PakTrendz',
      owner: 'chmuzamil',
      description: 'Pakistan trend tracking platform.',
      url: 'https://github.com/chmuzamil/paktrendz',
      githubUrl: 'https://github.com/chmuzamil/paktrendz',
      visibility: 'Private',
      category: 'SaaS',
      projectStatus: 'Production',
      githubHealth: 'Maintained',
      language: 'TypeScript',
      stars: 12,
      forks: 2,
      openIssues: 3,
      watchers: 4,
      lastCommitAt: '2026-06-01',
      connectedProjectIds: ['project_paktrendz'],
      connectedDomainIds: ['domain_viralpk'],
      connectedServerIds: ['server_main_vps'],
      deployment: 'VPS',
      liveUrl: 'https://viralpk.com',
    },
    {
      id: 'repo_founder_os',
      name: 'Founder OS',
      owner: 'chmuzamil',
      description: 'Personal founder dashboard.',
      url: 'https://github.com/chmuzamil/founder-os',
      githubUrl: 'https://github.com/chmuzamil/founder-os',
      visibility: 'Public',
      category: 'Internal Tool',
      projectStatus: 'Building',
      githubHealth: 'Maintained',
      language: 'JavaScript',
      stars: 5,
      forks: 1,
      openIssues: 0,
      watchers: 2,
      lastCommitAt: '2026-06-09',
      connectedProjectIds: ['project_founder_os'],
      connectedDomainIds: ['domain_founder_os'],
      connectedServerIds: ['server_main_vps'],
      deployment: 'VPS',
      liveUrl: 'https://founder-os.chaudhery.com',
    },
    {
      id: 'repo_pakdatakit',
      name: 'PakDataKit',
      owner: 'chmuzamil',
      description: 'Pakistan data utilities library.',
      url: 'https://github.com/chmuzamil/pakdatakit',
      githubUrl: 'https://github.com/chmuzamil/pakdatakit',
      visibility: 'Public',
      category: 'OSS Library',
      projectStatus: 'Production',
      githubHealth: 'Active',
      language: 'Python',
      stars: 28,
      forks: 6,
      openIssues: 2,
      watchers: 10,
      lastCommitAt: '2026-04-12',
      connectedProjectIds: ['project_pakdatakit'],
      deployment: 'GitHub',
    },
    {
      id: 'repo_pakdatakit_playground',
      name: 'PakDataKit Playground',
      owner: 'chmuzamil',
      description: 'Interactive playground for PakDataKit.',
      url: 'https://github.com/chmuzamil/pakdatakit-playground',
      githubUrl: 'https://github.com/chmuzamil/pakdatakit-playground',
      visibility: 'Public',
      category: 'OSS Library',
      projectStatus: 'Production',
      githubHealth: 'Active',
      language: 'TypeScript',
      stars: 8,
      forks: 1,
      openIssues: 0,
      watchers: 3,
      lastCommitAt: '2026-03-20',
      connectedProjectIds: ['project_pakdatakit'],
    },
    {
      id: 'repo_backupproof',
      name: 'BackupProof',
      owner: 'chmuzamil',
      description: 'Backup verification utility.',
      url: 'https://github.com/chmuzamil/backupproof',
      githubUrl: 'https://github.com/chmuzamil/backupproof',
      visibility: 'Public',
      category: 'Utility',
      projectStatus: 'Planning',
      githubHealth: 'Stale',
      language: 'Go',
      stars: 3,
      forks: 0,
      openIssues: 1,
      watchers: 1,
      lastCommitAt: '2025-11-02',
      connectedProjectIds: ['project_backupproof'],
      connectedDomainIds: ['domain_backupproof'],
    },
    {
      id: 'repo_kameti_khata',
      name: 'Kameti Khata App',
      owner: 'chmuzamil',
      description: 'Rotating savings group tracker.',
      url: 'https://github.com/chmuzamil/kameti-khata',
      githubUrl: 'https://github.com/chmuzamil/kameti-khata',
      visibility: 'Private',
      category: 'Mobile App',
      projectStatus: 'MVP',
      githubHealth: 'Maintained',
      language: 'Flutter',
      stars: 0,
      forks: 0,
      openIssues: 4,
      watchers: 1,
      lastCommitAt: '2026-05-18',
      connectedProjectIds: ['project_kameti_khata'],
      deployment: 'Mobile',
    },
  ]

  const projects = [
    {
      id: 'project_paktrendz',
      name: 'PakTrendz',
      slug: 'paktrendz',
      description: 'Pakistan trend tracking and viral content analytics platform.',
      status: 'Production',
      priority: 'High',
      category: 'SaaS',
      liveUrl: 'https://viralpk.com',
      domainIds: ['domain_viralpk'],
      repoIds: ['repo_paktrendz'],
      serverIds: ['server_main_vps'],
      subscriptionIds: ['subscription_viralpk_mail'],
      notes: 'Primary revenue project.',
    },
    {
      id: 'project_founder_os',
      name: 'Founder OS',
      slug: 'founder-os',
      description: 'Personal founder dashboard to manage domains, servers, GitHub repos, accounts, subscriptions, and renewals.',
      status: 'Building',
      priority: 'High',
      category: 'Internal Tool',
      liveUrl: 'https://founder-os.chaudhery.com',
      domainIds: ['domain_founder_os'],
      repoIds: ['repo_founder_os'],
      serverIds: ['server_main_vps'],
      subscriptionIds: [],
      notes: '',
    },
    {
      id: 'project_pakdatakit',
      name: 'PakDataKit',
      slug: 'pakdatakit',
      description: 'Open source Pakistan data utilities and playground.',
      status: 'Production',
      priority: 'Medium',
      category: 'OSS Library',
      liveUrl: '',
      domainIds: [],
      repoIds: ['repo_pakdatakit', 'repo_pakdatakit_playground'],
      serverIds: [],
      subscriptionIds: [],
      notes: '',
    },
    {
      id: 'project_backupproof',
      name: 'BackupProof',
      slug: 'backupproof',
      description: 'Backup verification and proof-of-restoration tooling.',
      status: 'Planning',
      priority: 'Medium',
      category: 'Utility',
      liveUrl: 'https://backupproof.dev',
      domainIds: ['domain_backupproof'],
      repoIds: ['repo_backupproof'],
      serverIds: [],
      subscriptionIds: [],
      notes: '',
    },
    {
      id: 'project_kameti_khata',
      name: 'Kameti Khata',
      slug: 'kameti-khata',
      description: 'Mobile app for rotating savings groups.',
      status: 'MVP',
      priority: 'Medium',
      category: 'Mobile App',
      liveUrl: '',
      domainIds: [],
      repoIds: ['repo_kameti_khata'],
      serverIds: [],
      subscriptionIds: [],
      notes: '',
    },
  ]

  const subscriptions = [
    {
      id: 'subscription_viralpk_mail',
      name: 'Mail support@viralpk.com',
      provider: 'SpaceMail by SpaceShip',
      cost: 273,
      currency: 'PKR',
      renewalDate: '2026-06-13',
      expiryDate: '2026-06-13',
      status: 'Expiring Soon',
      connectedProjectIds: ['project_paktrendz'],
      notes: '',
    },
    {
      id: 'subscription_openrouter',
      name: 'OpenRouter',
      provider: 'OpenRouter',
      cost: 400,
      currency: 'PKR',
      renewalDate: '2026-07-01',
      expiryDate: '2026-07-01',
      status: 'Active',
      connectedProjectIds: [],
      notes: 'AI API credits.',
    },
  ]

  return {
    domains,
    servers: [serverMainVps],
    repos,
    projects,
    accounts: [],
    subscriptions,
  }
}

export function isRecordsEmpty(records) {
  return Object.values(records).every((items) => !items?.length)
}
